### ISSUE TITLE
Question: What do you think of the overall arc, structure, and flow of the manuscript? Are there important sections missing that we should add? Or are there superfluous sections that we should remove?      

### ISSUE THREAD

**Issue by AileneKane** [AileneKane/bayes4cons#14]

**Comment by lizzieinvancouver** [comment]
I felt like the ms either needed to be shorter and cut a few thoughts (e.g., reduce the number of times we complain about NHT, cut/mv a case study or two) or be longer and develop a couple point in greater depth (e.g., adaptive management and Bayesian workflows, propagating uncertainty). Either way I suggest maybe beefing up the points in `Increasing use of Bayesian approaches' as I found that really interesting and unique. I would move that up and come back to at the end -- and try to center or connect our other points to it.

**Comment by AileneKane** [comment]
From Deirdre via email: I like the overall flow and think we address many the issues we should. I do think there are a few places were we should be more explicit on how Bayesian approaches fill the gaps common with frequentist analyses. I also think the case studies could be written to give explicit examples of how we would report results using a Bayesian analysis.

**Comment by AileneKane** [comment]
From Mao: Overall, the content looks clear and good to me. However, I was wondering if we might consider adjusting the order of some sections to improve the flow. For example, regarding the case studies and benefits, I think if could be easier to read if we could have the case study explained first, followed by the benefits related to that case study. This helps me understand the case study and concepts more easily without having to flip between pages.
