### ISSUE TITLE
alpha vs p-value

### ISSUE THREAD

**Issue by MarieAugerMethe** [AileneKane/bayes4cons#20]
In the section on moving beyond p-values, the significance level and the p-value are conflated. You set a significance level at the beginning of a study. In ecology the default is $\alpha = 0.05$. Here, and by convention, $\alpha$ is the significance level. You then do your analysis and calculate the p-value and check whether the p-value is smaller than the set significance level. 

In the text, there is many statement that says $\alpha < 0.05$ which does not make sense. Really, what we are checking is $p -value < \alpha$.

**Comment by AileneKane** [comment]
I believe that I resolved this...@Marie please check!

**Comment by MarieAugerMethe** [comment]
I think it's resolved. But I made a suggestion to change Type I error to significance level.
