### ISSUE TITLE
Revisiting title: Benefits of Bayesian Modelling Approaches For Conservation Science Under Climate Change

### ISSUE THREAD

**Issue by AileneKane** [AileneKane/bayes4cons#21]
@lizzieinvancouver @MarieAugerMethe @DeirdreLoughnan @hneyster @wangxm-forest and anyone i missed: please share thoughts on the title and, if you do not like, please share alternate ideas

**Comment by DeirdreLoughnan** [comment]
@AileneKane here are a few ideas for the title:

- Bayesian methods for Conservation Science
- Adopting Bayesian Methods in conservation Sciences
- The benefits of adopting Bayesian methods in Conservation Sciences

**Comment by hneyster** [comment]
There was consensus for: "Adopting Bayesian Methods in conservation Sciences" at our nov 1 meeting

**Comment by lizzieinvancouver** [comment]
I am offering a few more as I think we may interest more readers in a title that sounds more current and/or more specific to what's new or interesting in our article:

- How Bayesian approaches can help conservation science today
- Bayesian approaches for conservation science in the Anthropocene (or either of the above could be 'the value': The value of Bayesian approaches to conservation in the Anthropocene/today)
- Adaptive conservation science using Bayesian methods

**Comment by hneyster** [comment]
@lizzieinvancouver  good point. I like both of your suggestions with Anthro/today

**Comment by AileneKane** [comment]
@lizzieinvancouver I like "How Bayesian approaches can help conservation science today" and "Adaptive conservation science using Bayesian methods"

**Comment by AileneKane** [comment]
Another round of choices to discuss or vote on:

1. Adopting Bayesian Methods in Conservation Sciences
2. How Bayesian approaches can help conservation science today
3. Adaptive conservation science using Bayesian methods
4. Benefits of Bayesian Modelling Approaches For Conservation Science Under Climate Change

**Comment by AileneKane** [comment]
We settled on "Adaptive conservation science using Bayesian methods"!
