### ISSUE TITLE
All coauthors: read and provide feedback on new version of manuscript

### ISSUE THREAD

**Issue by AileneKane** [AileneKane/bayes4cons#22]
I'm especially wanting feedback on:

1.  the order and flow/integration of the different pieces. Does it work? If not, what should we add/change?
2. What case studies do we want to keep and how should we integrate them into the main text (we discussed a box of case studies vs a section in the text)?

**Comment by lizzieinvancouver** [comment]
@AileneKane Sorry I was slow on this! I just pushed edits. In general, I love the new short form of the paper and think we could wrap it up quickly. I think it needs a little re-ordering of sentences/paragraphs here or there and less passive voice, nominalizations and all the adjectives that make something super exact but sort or weighed down (say 'integrated approaches' when needed and more often say just approaches for example).

**Comment by AileneKane** [comment]
Thank you, coauthors, for your helpful feedback and additions!!!
