### ISSUE TITLE
Help with Subtitles

### ISSUE THREAD

**Issue by AileneKane** [AileneKane/bayes4cons#23]
Current subtitle of "Benefits of Bayesian Modelling Approaches for Conservation Science" is almost the same as the manuscript title. How should we change that? Also, please help improve subtitles under this heading, which are currently:

1. "Iterative workflows that align with adaptive management practices in conservation"
2. "Flexible frameworks for accommodating complex and incomplete data"
3. "Integrated approaches for quantifying and propagating uncertainty"

**Comment by AileneKane** [comment]
Replace 1 with  "Iterative workflows for adaptive management"

**Comment by AileneKane** [comment]
Replace 2 with "Flexible frameworks for complex and incomplete data"

**Comment by AileneKane** [comment]
"

**Comment by lizzieinvancouver** [comment]
"Flexible frameworks for complex data" seems better, complex data includes incomplete.

I think the last one could be just: Quantifying and propagating uncertainty

**Comment by AileneKane** [comment]
Made all these changes
